name: Inno Store Web UI

on:
  push:
    branches:
      - main
      - functions
    paths:
      - 'inno-store-webui/**'
      - '.github/workflows/inno-store-webui.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inno-store-webui

    steps:
      - uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm run ci:bundle-azure-deployment

      - name: 'Deploy to Azure Web App'
        id: 'deployToAzure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ secrets.PROJECT_NAME }}-webui'
          slot-name: 'production'
          package: 'inno-store-webui/dist/dist.zip'

      - name: 'Notify Slack'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Deployed WebUI'
          SLACK_FOOTER: ${{ steps.deployToAzure.outputs.webapp-url }}
          SLACK_USERNAME: 'InnoVaderBot'
